### ISSUE TITLE
pip install alertapi FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'

### ISSUE THREAD

**Issue by akademsubotnik** [CrispCrow/AlertAPI#2]
I am trying to install alertapi with pip, but get the below error when I try to install 

```
(kievairalarm_bot) PS C:\Users\Chuwi\PycharmProjects\pythonProject1> pip install alertapi
Collecting alertapi
  Downloading alertapi-0.0.5.tar.gz (14 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [19 lines of output]
      Traceback (most recent call last):
        File "C:\Users\Chuwi\Projects\pythonProject\kievairalarm_bot\Lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 351, in <module>
          main()
        File "C:\Users\Chuwi\Projects\pythonProject\kievairalarm_bot\Lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Chuwi\Projects\pythonProject\kievairalarm_bot\Lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Chuwi\AppData\Local\Temp\pip-build-env-6a6gzam5\overlay\Lib\site-packages\setuptools\build_meta.py", line 355, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\Chuwi\AppData\Local\Temp\pip-build-env-6a6gzam5\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in _get_build_requires
          self.run_setup()
        File "C:\Users\Chuwi\AppData\Local\Temp\pip-build-env-6a6gzam5\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 70, in <module>
        File "<string>", line 51, in parse_requirements_file
      FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

[notice] A new release of pip available: 22.3.1 -> 23.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip
(kievairalarm_bot) PS C:\Users\Chuwi\PycharmProjects\pythonProject1> 
```

**Comment by akademsubotnik** [comment]
This is fixed with $pip install alertapi==0.0.4
Thanks @CrispCrow!
